all: reverseInt reverseInt_fast

reverseInt: ReverseInt.cpp
	g++ -v ReverseInt.cpp -o reverseInt
	
reverseInt_fast: ReverseInt_fast.cpp
	g++ -v ReverseInt_fast.cpp -o reverseInt_fast

clean:
	rm -rf *o reverseInt reverseInt_fast
