all: longestPrefix longestPrefix_vert longestPrefix_divide longestPrefix_binary

longestPrefix: longestPrefix_horiz.cpp
	g++ -v longestPrefix_horiz.cpp -o longestPrefix

longestPrefix_vert: longestPrefix_vert.cpp
	g++ -v longestPrefix_vert.cpp -o longestPrefix_vert

longestPrefix_devide: longestPrefix_devide.cpp
	g++ -v longestPrefix_devide.cpp -o longestPrefix_devide

longestPrefix_binary: longestPrefix_binary.cpp
	g++ -v longestPrefix_binary.cpp -o longestPrefix_binary

clean:
	rm -rf *o longestPrefix longestPrefix_vert longestPrefix_divide logestPrefix_binary
